- name: Java
  logo: java
  url: https://www.java.com/en/
  color: ffa500
  projects:
    - https://github.com/ShubhamPatilsd/space-catch
    - https://github.com/ShubhamPatilsd/Cyber-Wizards-FTC-Robotics-Ultimate-Goal-2020
    - https://github.com/ShubhamPatilsd/simple-pad

    - https://github.com/ShubhamPatilsd/NetworkScannerRickRoll
    - https://github.com/ShubhamPatilsd/UpperLowerCaseTextMaker
 
