- name: profile_stack
  uses: Matt-Gleich/profile_stack@v1.4.1

name: Profile Stack

on:
  push:
    branches:
      - master

jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Matt-Gleich/profile_stack@master
